# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
# collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude: ['node_modules']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems: [jekyll-paginate, octopress-autoprefixer, octopress-paginate]

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.0
baseurl: "" # does not include hostname

# Outputting
permalink:  /:title.html
paginate: 6
per_page: 1
paginate_path: /posts/page:num/
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

include: ['_pages']

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: :compressed
  sass_dir: _sass
